### ISSUE TITLE
Support V3 networks

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/nodes-explorer#12]
- Support v3 devnet, testnet
- if there's any difference in data we should just transform the minimal needed in the UI
- data for v3 should be aggregated from the grid proxy (mainly nodes, gateways and farms)

* no major changes in UI

**Comment by scottyeager** [comment]
There are a couple of issues with the implementation:

1. No mainnet option for Grid 3
2. Total nodes does not reflect the selection of Grid 2/3 when `all` is selected
3. Cores/ram/disk aren't shown

**Comment by dmahmouali** [comment]
> There are a couple of issues with the implementation:
> 
> 1. No mainnet option for Grid 3


the first point will be supported after mainnet upgrade, it will be tracked in this issue https://github.com/threefoldtech/nodes-explorer/issues/19


> 2. Total nodes does not reflect the selection of Grid 2/3 when `all` is selected

It works now, please check again after the updates

> 3. Cores/ram/disk aren't shown

they are shown in node details
![image](https://user-images.githubusercontent.com/36021484/151700691-1b883e3e-164d-4851-a69e-4dad56c3a85c.png)

thank you for your comment @scottyeager

**Comment by scottyeager** [comment]
Thanks for the update @dmahmouali. Total nodes shown per network looks better now.

Regarding item 3, I was referring to the totals show at the top. These are loading now, but I noticed that for Grid 3 it lists `EB` and `ZB` rather than `GB` and `TB`.

New issue I've noticed: version numbers on Grid 3 don't look right. I think this should display the Zos version, such as `3.0...`

**Comment by dmahmouali** [comment]
Fixed @scottyeager
